---
title: Neural OScillatory Dynamics and Cognition - A Neurohysiological Study
author:
  - name: Rahul Venugopal
    affil: 1
  - name: Arun Sasidharan
    affil: 1
affiliation:
  - num: 1
    address: Centre for Consciousness Studies, NIMHANS, Bengaluru
  - num: 2
    address: National Institute of Advanced Studies, NIAS, Bengaluru
column_numbers: 3
logoright_name: "NIMHANS.png"
logoleft_name: "CCS.png"
author_textcol: "white"
columnline_style: "dashed"
output: 
  posterdown::posterdown_html:
    self_contained: false
---


# Introduction

Welcome to `posterdown` ! This is my attempt to provide a semi-smooth workflow for those who wish to take their R Markdown skills to the conference world. Most features from R Markdown are available in this package such as Markdown section notation, figure captioning, and even citations like this one [@R-rmarkdown]. The rest of this example poster will show how you can insert typical conference poster features into your own document. 

## Objectives

1. Easy to use reproducible poster design. 
2. Integration with R Markdown.
3. Easy transition from `posterdown` to `pagedown` report or manuscript documents [@R-pagedown].

### More Objectives

1. Easy to use reproducible poster design. 
2. Integration with R Markdown.

# Methods

This package uses the same workflow approach as the R Markdown you know and love. Basically it goes from RMarkdown > Knitr > Markdown > Pandoc > HTML/CSS > PDF. You can even use the bibliography the same way [@R-posterdown].

# Results

Usually you want to have a nice table displaying some important results that you have calculated. In `posterdown` this is as easy as using the `kable` table formatting you are probably use to as per typical R Markdown formatting.

# Next Steps

Aliquam sed faucibus risus, quis efficitur erat. Vestibulum semper mauris quis tempus eleifend. Aliquam sagittis dictum ipsum, quis viverra ligula eleifend ut. Curabitur sagittis vitae arcu eget faucibus. In non elementum felis. Duis et aliquam nunc. Nunc pulvinar sapien nunc, vel pretium nisi efficitur in. Fusce fringilla maximus leo et maximus. Fusce at ligula laoreet, iaculis mi at, auctor odio. Praesent sed elementum justo. Aenean consectetur risus rhoncus tincidunt efficitur. Praesent dictum mauris at diam maximus maximus [@R-posterdown].

# Conclusion

Try `posterdown` out! Hopefully you like it!

# References
